db: h2
spring:
  mvc:
    throw-exception-if-no-handler-found: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    data: classpath*:db/${db}/data-${db}.sql
    schema: classpath*:db/${db}/schema.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
server:
  port: 8081

jwt:
  secret: MjAyMSBjYXBzdG9uZSBkZXNpZ24gcHJvamVjdCBwb29tLWk=

ncs:
  accessKey: ${NCS_ACCESS_KEY}
  secretKey: ${NCS_SECRET_KEY}
  serviceId: ${NCS_SERVICE_ID}
  from: ${NCS_FROM}

kakao:
  clientId: ${KAKAO_CLIENT_ID}
  clientSecret: ${KAKAO_CLIENT-SECRET}
  redirectionURI: ${KAKAO_REDIRECTION_URI}
  tokenURI: ${KAKAO_TOKEN_URI}
  userinfoURI: ${KAKAO_USERINFO_URI}

google:
  clientId: ${GOOGLE_CLIENT_ID}
  clientSecret: ${GOOGLE_CLIENT-SECRET}
  redirectionURI: ${GOOGLE_REDIRECTION_URI}
  tokenURI: ${GOOGLE_TOKEN_URI}
  userinfoURI: ${GOOGLE_USERINFO_URI}

naver:
  clientId: ${NAVER_CLIENT_ID}
  clientSecret: ${NAVER_CLIENT-SECRET}
  tokenURI: ${NAVER_TOKEN_URI}
  userinfoURI: ${NAVER_USERINFO_URI}



lombok:
  anyConstructor:
    addConstructorProperties: true

slack:
  url: ${SLACK_POST_URL}
  token: ${SLACK_TOKEN}
  channel: ${SLACK_CHANNEL}