#PUT http://localhost:8080/api/members/modified
#Content-Type: application/json
#
#{
#  "email": "migni@gmail.com",
#  "password": "1234",
#  "modified_properties": {
#    "name": "migni2"
#  }
#}

#POST http://localhost:8080/api/members/join
#Content-Type: application/json
#
#{
#  "name": "steve",
#  "phone_number": "010-1111-1111",
#  "email": "steve@gmail.com",
#  "password": "1234",
#  "nick": "steve",
#  "address": "Daejeon"
#}

#POST http://localhost:8080/api/boards
#Content-Type: application/json
#
#{
#  "title": "두번째 게시글",
#  "contents": "두번째 게시글입니다."
#}

#PUT http://localhost:8080/api/boards/1
#Content-Type: application/json
#
#{
#  "email": "steve@gmail.com",
#  "contents": "첫번째 게시글의 내용이 변경되었습니다."
#}

#GET http://localhost:8080/api/boards/1

#DELETE http://localhost:8080/api/boards/2

#POST http://localhost:8080/api/login
#Content-Type: application/json
#
#{
#  "email": "steve@gmail.com",
#  "password": "1234"
#}

#POST http://localhost:8080/api/boards/1/comments
#Content-Type: application/json
#
#{
#  "contents": "첫번째 댓글입니다."
#}

#PUT http://localhost:8080/api/boards/1/comments/1
#Content-Type: application/json
#
#{
#  "contents": "첫번째 댓글은 수정되었습니다."
#}

#DELETE http://localhost:8080/api/boards/1/comments/1